name: ModIsom
version: "3.1.0"
license: "GPL-2.0-or-later"
date: 2026-01-09
description: |
    Computing automorphisms and checking isomorphisms for modular group algebras of finite p-groups

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Diego Garcia-Lucas
      url: mailto:diego.garcial@usc.es
    - name: Leo Margolis
      url: http://www.margollo.github.io
    - name: Tobias Moede
      url: https://www.tu-braunschweig.de/iaa/personal/moede

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/
    - name: Leo Margolis
      url: http://www.margollo.github.io

GAP: ">=4.10"

needed-pkgs:
    - name: "Polycyclic"
      version: ">=1.0"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "LAGUNA"
      version: ">=3.8.0"
      url: "https://gap-packages.github.io/laguna"

www: https://gap-packages.github.io/modisom/
readme: README.md
packageinfo: https://gap-packages.github.io/modisom/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/modisom/releases/download/v3.1.0/modisom-3.1.0.tar.gz

abstract: |
    The <span class="pkgname">ModIsom</span> package contains various methods for computing with nilpotent associative algebras. In particular, it contains a method to determine the automorphism group and to test isomorphis of such algebras over finite fields and of modular group algebras of finite p-groups, and it contains a nilpotent quotient algorithm for finitely presented associative algebras and a method to determine Kurosh algebras.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    modular isomorphism problem, automorphism group, isomorphism testing, nilpotent algebras, nilpotent quotient, Kurosh algebras.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>EGKMM26</span>]   <b class='BibAuthor'>Eick, B., Garcia-Lucas, D., Konovalov, O., Margolis, L. and Moede, T.</b>,
     <i class='BibTitle'>ModIsom, Computing automorphisms and checking isomorphisms for modular group algebras of finite p-groups,
             Version 3.1.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/modisom/">https://gap-packages.github.io/modisom/</a></span>.
    </p>
    

bibtex: |
    @misc{ ModIsom,
      author =           {Eick,  B.  and Garcia\texttt{\symbol{45}}Lucas, D. and
                          Konovalov, O. and Margolis, L. and Moede, T.},
      title =            {{ModIsom},   {Computing   automorphisms  and  checking
                          isomorphisms  for  modular  group  algebras  of finite
                          p\texttt{\symbol{45}}groups}, {V}ersion 3.1.0},
      month =            {Jan},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href        {https://gap-packages.github.io/modisom/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{modisom/}}},
      keywords =         {modular   isomorphism   problem;  automorphism  group;
                          isomorphism  testing;  nilpotent  algebras;  nilpotent
                          quotient; Kurosh algebras},
      printedkey =       {EGKMM26}
    }

