#!/bin/sh
set -e

echo "TeXing documentation"
# this was a failed try of Max to update this file. Will comment it out using several ###
#### delete old stuff to avoid spurious or "hidden errors" caused by their presence  
###rm -f manual.aux manual.pdf manual.idx manual.ilg manual.ind manual.lab manual.log manual.six manual.toc
# TeX the manual
tex manual
###pdftex manual
# ... and build its bibliography
bibtex manual
# TeX the manual again to incorporate the ToC 
tex manual
tex manual
#### pdftex manual
# ... and build the index
../../../doc/manualindex manual
# Finally TeX the manual again to get cross-references right
tex manual
pdftex manual; pdftex manual
#### pdftex manual

# The HTML version of the manual
rm -rf ../htm
mkdir ../htm
#### mkdir -p ../htm
echo "Creating HTML documentation"
../../../etc/convert.pl -i -u -c -n ModIsom . ../htm
